language: php

php:
  - 7.1
  - 7.2

services:
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer update
  - composer require php-coveralls/php-coveralls --dev

script: vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
